version: '3.8'

services:
  webtv:
    build: .
    container_name: mapim-webtv
    restart: unless-stopped
    env_file:
      - config.env
    volumes:
      - ./assets:/app/assets:ro
    network_mode: bridge
